version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - hms-network

  notification-service:
    build: .
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_USER=bktesthms@gmail.com
      - SMTP_PASSWORD=iedb bjuh kwlj pyks
      - FROM_EMAIL=bktesthms@gmail.com
    command: ["./notification-service"]

networks:
  hms-network:
    external: true
