version: '3.8'

services:
  notification-service:
    build: .
    ports:
      - '5006:5006'
    environment:
      - PORT=5006
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
    command: ["./wait-for-it.sh", "rabbitmq", "./main"]

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
