version: '3.8'

services:
  prescription-management:
    build: .
    ports:
      - '5005:5005'
    env_file:
      - .env
    depends_on:
      - prescription-db
    command: sh -c "npm start"
    networks:
      - hms-network

  prescription-db:
    image: mongo
    networks:
      - hms-network
   
networks:
  hms-network:
    external: true