version: '3.8'

services:
  appointment-scheduling:
    build: .
    ports:
      - '5003:5003'
    env_file:
      - .env
    depends_on:
      - appointment-db
    command: sh -c "npx sequelize-cli db:migrate && npm start"

  appointment-db:
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appointmentdb
