version: '3.8'

services:
  medical-records:
    build: .
    ports:
      - '5004:5004'
    env_file:
      - .env
    depends_on:
      - medical-records-db
    command: sh -c "npx sequelize-cli db:migrate && npm start"

  medical-records-db:
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medicalrecordsdb
