version: '3.8'

services:
  patient-management:
    build: .
    ports:
      - '5002:5002'
    env_file:
      - .env
    depends_on:
      - patient-db
    command: sh -c "npx sequelize-cli db:migrate && npm start"
    volumes:
      - .://usr/src/app

  patient-db:
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: patientdb
